---
- hosts: all
  become: yes
  tasks:
    - name: Composer | Install Composer latest-stable
      get_url:
        url: '{{ composer_url }}'
        checksum: 'sha256:{{ composer_url }}.sha256sum'
        dest: /usr/local/bin/composer.phar
        mode: 0755

    - name: Composer | Symlink composer.phar
      file:
        src: composer.phar
        dest: /usr/local/bin/composer
        state: link

...